### ISSUE TITLE
Issue JQL Matcher

### ISSUE THREAD

**Issue by alex131290** [sford/yet-another-commit-checker#60] opened 2015-06-25 14:06 UTC
Hi, 
I'm using the JQL matcher.
Here is the query that i'm using : assignee = currentUser() and status != "closed"

The thing is that the error message that the user is getting is not friendly, for example
"remote: refs/heads/devel: 74c9328a421478d070ba3a0300eb1afb969161e7: IssueKey{TLVT-164}: JIRA Issue does not match JQL Query: assignee = currentUser() and status != "closed"
"
Considering the fact that i'm adding a custom message (error) in the textbox. the error that the user will see, is going to be the same each time, and the user won't understand what was the actual issue (assignee issue or status issue)
Any idea how to solve it?

**Comment by sford** [comment] 2015-06-25 15:16
Couldn't you make the custom error message something that is easy to understand? For instance:

> Issue is not in the correct state. Please ensure that it is assigned to yourself and hasn't been closed.

This immediately lets the user know that the problem is with the JIRA issue, and then outlines your JIRA commit policy in a human readable form, which also tells the user what they need to check.

**Comment by alex131290** [comment] 2015-06-25 16:17
I can use this message, but is there any way that we can parse the query in your code and separate each part of the query and check the response, if the response of one of the parts will return an error we'll show the relevant message to the user

**Comment by sford** [comment] 2015-06-27 17:48
All depends on how complicated your parser is. For your query, `assignee = currentUser() and status != "closed"`, you could theoretically split on "and" and run each part. JQL is much more expressive than that, and you can run into situations where you can't simply split on "and" or split the query into parts. For example:

* (project="ABC" and assignee is not empty) OR (project="FOO" and assignee=currentUser())
* project="and"

You could certainly spend a lot of time and effort on handling these cases, but there are still queries were you can't split it up (like ones using or's). At some point, you would be adding a lot of code and complexity for a questionable amount of gain compared to a simple message that says "Please make sure the issue is assigned and open".

**Comment by sford** [comment] 2015-08-31 01:12
Closing. Feel free to re-open if you have other questions.

**Closed by sford** 2015-08-31 01:12 UTC
