### ISSUE TITLE
Is it possible to control size of Commit message

### ISSUE THREAD

**Issue by sdmello14** [sford/yet-another-commit-checker#219] opened 2019-07-12 01:06 UTC
Our Organisation is using YACC as plugin with BitBucket to protect the repo. with appropriate regex pattern, JIRA and few other checks.

Recently we found YACC by default has commit message restricted to ~2565 characters and therefore we receive "Pre-receive hook declined" error while our ETL tool  configured with BitBucket attempts to push some predefined commit messages greater than 2565 characters.

Is there any way to increase/control the size of commit in YACC?

Please advise

**Comment by sford** [comment] 2019-07-12 14:30
I am not immediately aware of any limits around max length of commit messages. Do you have example git output when this occurs? Is YACC really the one that is rejecting the push?

**Comment by gsylvie** [comment] 2019-07-13 07:53
Any chance this is a duplicate of #191?

(which should probably be closed, since it's Java's fault, and not YACC's fault).

**Comment by sford** [comment] 2019-07-13 18:07
@gsylvie Great eye on #191. Indeed looks like a duplicate.

@sdmello14 Can you try the suggested workaround to see if it fixes your issues? Sounds like root issue is Java limitation. If you are matching multiple lines of text, you can probably try the workaround as-is: `(?s).*`.

**Comment by sdmello14** [comment] 2019-07-28 21:38
Thanks @sford,@gsylvie for your reply.

Actuallly, I don't have multiple matching lines in commit message. An eclipse IDE forces the commit pattern and every time it appends the log to the commit message which makes it very huge (>2585).

If Java is the cause behind the push error, Could you please share an substitution to my regex pattern : (ATA-[0-9]+)(.|\n)*

please advise

**Comment by sdmello14** [comment] 2019-07-28 22:15
Is regex : (ATA-[0-9]+)(.|\n)*  = (ATA-[0-9]+)(?s).*      
??

**Comment by sford** [comment] 2019-07-29 03:15
@sdmello14 Looks about right. Give it a try to see how it works.

**Comment by sayandeys** [comment] 2019-07-29 15:37
@sdmello14 is it possible to make YACC verify only the last commit message instead of checking all the commit messages.
Use case: If someone adds a commit message that doesn't follow the pattern, YACC will reject it. Now if we have a new commit message with the correct pattern, YACC will still reject it because the old commit message doesn't follow the pattern.

**Comment by sford** [comment] 2019-07-29 18:13
@sayandeys Sure, that is technically possible but defeats the purpose of YACC because it would be allowing commits that don't follow requirements because it only checks the last commit.

For that use case, YACC rejects it and developer can fix by doing something like `git commit --amend`.

**Comment by sford** [comment] 2019-09-09 19:41
Closing as duplicate of #191

**Closed by sford** 2019-09-09 19:41 UTC
Labels: resolution: duplicate, type: bug

**Comment by george-vulov** [comment] 2020-09-02 19:30
[Version 2.0.0](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions) detects these type of regex complexity failures and offers an informative error message rather than throwing an exception.
