### ISSUE TITLE
How to enable YACC to block the commit messages made from Bitbucket GUI.

### ISSUE THREAD

**Issue by kpremk** [sford/yet-another-commit-checker#194] opened 2018-10-16 09:26 UTC
Bitbucket latest version is supporting the saving the file and applying commit messages from Bitbucket GUI interface. Though YACC hook is enabled for that Repository, it is not blocking the commit messages.

**Comment by rishibamba** [comment] 2019-01-03 11:16
Seems to be a duplicate of an open issue. [140](https://github.com/sford/yet-another-commit-checker/issues/140)

**Closed** 2019-09-09 19:44 UTC
Labels: resolution: duplicate, type: feature
