### ISSUE TITLE
Enable / Configure via REST results in 400 Bad Request

### ISSUE THREAD

**Issue by roxspring** [sford/yet-another-commit-checker#39] opened 2014-11-26 12:33 UTC
I'm using the REST API to try and keep plugin configurations synchronized across a project.  When I configure yacc (or enable it with a configuration)

```
PUT /rest/api/1.0/projects/DPA/repos/utilities/settings/hooks/com.isroot.stash.plugin.yacc:yaccHook/enabled/

{"commitMessageRegex":"","requireJiraIssue":true,"ignoreUnknownIssueProjectKeys":true,"issueJqlMatcher":"resolution = Unresolved","excludeByRegex":""}

Status: 400 Bad Request

{"errors":[{"context":"issueJqlMatcher","message":"Unable to validate JQL query with JIRA because there was an unexpected exception. Please see Stash logs.","exceptionName":null}]}
```

When configuring manually it's clear that there is no problem with the issueJqlMatcher and I'm unable to find any reference to any of this in ANY logs!

Please help!

**Comment by sford** [comment] 2015-04-23 04:03
I just tried using the Stash API to configure a JQL issue matcher and it worked fine for me. I was able to reproduce the "unexpected exception" error by shutting down JIRA, which is expected because it couldn't connect to JIRA. My Stash log had a "connection refused" exception log message indicating this.

Going to close this, but feel free to re-open if you continue to have problems.

**Closed by sford** 2015-04-23 04:03 UTC

**Comment by george-vulov** [comment] 2020-08-03 18:45
Here's some relevant documentation on how to enable YACC via the REST API: [How to modify YACC settings programmatically](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1484652654/How+to+modify+YACC+settings+programmatically).
