### ISSUE TITLE
Default Config of YACC is winning in Repository Config when it is disabled

### ISSUE THREAD

**Issue by duderino65** [sford/yet-another-commit-checker#174] opened 2018-02-22 10:39 UTC
Hi,

first, thanks for this plugin. So far it works very good for our team. As admin I have some Issues regarding YACC Configuration.

YACC 1.18 & Bitbucket 5.3.0

I set up our normal configuration in the Default Config of the YACC Plugin. My thoughts have been, that I just need to activate YACC in the Repo to get the Default Config easily into it. Unfortunatelly the Default Config is active even if the plugin is deactivated in the Repository. As Workaround I've deselected some checkboxes of the Default Config, so I don't have to write the Expressions every time.

Kind regards
Andreas

**Comment by nathanbedford** [comment] 2018-03-15 19:01
Hi Andreas,

My experience (and also from the docs) is that what you are experiencing is by design:

> Global settings will apply to all repositories that don't have YACC enabled per-repository. Once YACC is enabled for a repository, then all global settings will be superseded by the per-repository settings for that particular repository.
https://github.com/sford/yet-another-commit-checker#how-to-configure

So all your repos will get that default config right away, without you doing anything.  If you want a repo to NOT use the default settings, then you'd have to enable yacc for that repo and change the settings there.

I'm running into an issue where, once I've enabled and customized config for a repo, I can't get that repo to go back to using the default settings (#175).  Once we get some answers on that it might be useful to you too.

Hope that helps!

**Comment by duderino65** [comment] 2018-03-21 08:31
Hi Nathan,
thanks for your reply. I will use the workaround. Thats ok for me.

Kind regards
Andreas

**Comment by sford** [comment] 2018-12-01 21:33
Should be fixed in 1.19. See GH-175.

**Closed** 2018-12-01 21:34 UTC
Labels: resolution: duplicate, resolution: fixed, type: bug
